/* =============================== REPORTS =============================== */
const inrP = (v, d = 2) => inr(v, d).replace('₹', 'Rs.');
const METHOD = [
  'Data sources: bank statements, KYC replies, bank login/IP logs, CDR, IPDR, NCRP trail and SMS/OTP records as imported (see Source Documents with SHA-256 hashes). Every figure is traceable to file, sheet/page and row.',
  'Transaction matching priority: (1) identical UTR/RRN, (2) identical transaction reference, (3) beneficiary account / masked account / UPI ID / mobile named in the debit narration, (4) same amount within the configured time window where exactly one candidate exists. Ambiguous candidates are not linked automatically.',
  'Traced amount: the disputed amount entering an account is followed into later debits of that account (traced-funds-first unless set to proportional), limited by the running balance and the configured holding period. "Possibly available" is the traced amount not debited as of the last statement row and must be confirmed with the bank.',
  'Telecom and IP correlation report co-occurrence in time (± window). Cell-site data shows the serving cell, not an exact location. A public IP identifies a subscriber only together with exact time and, for CGNAT, the source port. Correlations and leads are investigative indicators and are not conclusions of guilt.'
];
function pdfDoc(title, landscape = true) {
  const { jsPDF } = window.jspdf; const doc = new jsPDF({ orientation: landscape ? 'l' : 'p', unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth(), H = doc.internal.pageSize.getHeight(); const m = S.cur.meta;
  const st = { doc, W, H, y: 70, title };
  st.header = () => { doc.setFillColor(11, 20, 38); doc.rect(0, 0, W, 44, 'F'); doc.setTextColor(103, 232, 249); doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.text('CFITS', 30, 27); doc.setTextColor(255, 255, 255); doc.setFontSize(10); doc.text(title, 80, 27); doc.setTextColor(252, 165, 165); doc.setFontSize(8.5); doc.text(`${m.conf} — ${m.crimeNo || m.id} — ${m.ps}`, W - 30, 27, { align: 'right' }); doc.setTextColor(20, 20, 20); };
  st.footer = () => { const n = doc.internal.getNumberOfPages(); for (let i = 1; i <= n; i++) { doc.setPage(i); doc.setFontSize(7.5); doc.setTextColor(110, 110, 110); doc.text(`Generated ${nowStamp()} by ${S.user.email} (IO: ${m.io || '—'}) · CFITS v${CONFIG.VERSION} · Investigation-support analysis — verify against source records`, 30, H - 18); doc.text(`Page ${i} of ${n}`, W - 30, H - 18, { align: 'right' }); doc.setTextColor(200, 40, 40); doc.text(m.conf, W / 2, H - 30, { align: 'center' }); } };
  st.header();
  st.need = h => { if (st.y + h > H - 50) { doc.addPage(); st.header(); st.y = 70; } };
  st.h = t => { st.need(40); doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(14, 116, 144); doc.text(t, 30, st.y); st.y += 8; doc.setDrawColor(34, 211, 238); doc.line(30, st.y, W - 30, st.y); st.y += 14; doc.setTextColor(20, 20, 20); };
  st.p = (t, size = 9) => { doc.setFont('helvetica', 'normal'); doc.setFontSize(size); const lines = doc.splitTextToSize(String(t), W - 60); for (const l of lines) { st.need(13); doc.text(l, 30, st.y); st.y += 12; } st.y += 4; };
  st.kv = rows => { doc.autoTable({ startY: st.y, body: rows, theme: 'plain', styles: { fontSize: 8.5, cellPadding: 2.5 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 170, textColor: [60, 70, 90] } }, margin: { left: 30, right: 30, top: 60 }, didDrawPage: d => { if (d.pageNumber > 1 || doc.internal.getNumberOfPages() > 1) st.header(); } }); st.y = doc.lastAutoTable.finalY + 12; };
  st.table = (head, body, opt = {}) => { if (!body.length) { st.p('— none —', 8); return; } doc.autoTable(Object.assign({ startY: st.y, head: [head], body: body.map(r => r.map(v => v == null ? '' : String(v))), theme: 'grid', styles: { fontSize: 7.2, cellPadding: 2.5, overflow: 'linebreak', lineColor: [210, 215, 225] }, headStyles: { fillColor: [15, 27, 49], textColor: [220, 240, 255], fontStyle: 'bold' }, alternateRowStyles: { fillColor: [244, 247, 251] }, margin: { left: 30, right: 30, top: 60 }, didDrawPage: () => st.header() }, opt)); st.y = doc.lastAutoTable.finalY + 14; };
  st.save = name => { st.footer(); doc.save(`CFITS_${fileSafe(m.id)}_${fileSafe(name)}_${isoDate(nowWall())}.pdf`); audit('Generated report', name); };
  return st;
}
function caseKv() { const m = S.cur.meta; return [['Case ID', m.id], ['FIR / Crime No.', m.crimeNo], ['Police Station', m.ps], ['District', m.district], ['Investigating Officer', m.io], ['Case type', m.type], ['Registered on', m.regDate], ['Status', m.status], ['Confidentiality', m.conf], ['Remarks', m.remarks]]; }
function layerRows() { const d = D(); return Array.from(d.byLayer.entries()).sort((a, b) => a[0] - b[0]).map(([l, b]) => [layerName(l), b.accts, inrP(b.tin), inrP(b.cash), inrP(b.retained)]); }
function acctRows(filter) { const d = D(); return Array.from(d.acctRes.entries()).filter(filter || (() => true)).sort((a, b) => a[1].layer - b[1].layer || b[1].tin - a[1].tin).map(([id, r]) => { const a = IX.acctById.get(id); return [layerName(r.layer), a.acctNo, a.holder, a.bank, a.ifsc, inrP(r.tin), inrP(r.tout), inrP(r.cash), inrP(r.retained), r.hasStmt ? 'Yes' : 'PENDING', acctNumbers(a).join(', ')]; }); }
const flowRow = f => { const t = IX.txById.get(f.debit) || {}; return [f.id, layerName(f.layerFrom), (IX.acctById.get(f.fromAcct) || {}).acctNo, f.toAcct ? (IX.acctById.get(f.toAcct) || {}).acctNo : f.toExt.label, fmtDT(f.ts, f.hasTime), inrP(f.amt), inrP(f.full), t.utr || '', f.gap != null ? durTxt(f.gap) : '', f.strength, (f.reasons || []).join('; '), `${t.src ? t.src.file + ' ' + (t.src.page ? 'p' + t.src.page + ' ' : '') + 'r' + t.src.row : ''}`]; };

function reportComplete(scope = 'full') {
  const c = S.cur; const d = D(); const t = d.tot; const R = pdfDoc(scope === 'summary' ? 'Case Summary Report' : 'Complete Investigation Report');
  R.h('1. Case details'); R.kv(caseKv());
  R.h('2. Summary of findings (data-supported)');
  R.kv([['Amount reported lost (disputed transactions)', `${inrP(t.loss)} in ${t.seeds} transaction(s) from ${t.compAccts} complainant account(s)`], ['Traced into Layer 1 accounts', inrP(t.traced)], ['Accounts in trail', `${d.acctRes.size} (deepest layer L${t.maxLayer})`], ['Cash / ATM withdrawn from trail', inrP(t.cash)], ['Traced amount possibly still available', inrP(t.retained) + ' (confirm with banks)'], ['Onward transfers to unidentified / not-yet-uploaded accounts', inrP(t.unresolved + t.pending)], ['Data imported', `${c.txns.length} transactions · ${c.accts.length} accounts · ${c.telecom.cdr.length} CDR events · ${c.ip.logs.length} login records · ${c.ip.ipdr.length} IPDR sessions`]]);
  R.table(['Layer', 'Accounts', 'Traced in', 'Cash out', 'Possibly available'], layerRows());
  if (scope === 'summary') { R.h('Priority leads'); R.table(['Priority', 'Observation', 'Supporting data'], buildLeads().filter(l => l.sev === 'high').slice(0, 40).map(l => [l.sev.toUpperCase(), l.title, l.detail])); return R.save('Case_Summary'); }
  R.h('3. Methodology & limitations'); METHOD.forEach(p => R.p(p));
  R.h('4. Disputed transactions (seeds)'); R.table(['Txn', 'Account', 'Date/Time', 'Amount', 'Channel', 'UTR', 'Narration', 'Source'], d.seeds.map(s => [s.id, (IX.acctById.get(s.acctId) || {}).acctNo, fmtDT(s.ts, s.hasTime), inrP(s.dr), s.channel, s.utr, s.narr.slice(0, 70), s.src.file + ' r' + s.src.row]));
  R.h('5. Accounts in the money trail'); R.table(['Layer', 'Account', 'Holder', 'Bank', 'IFSC', 'Traced in', 'Onward', 'Cash', 'Possibly avail.', 'Statement', 'Linked numbers'], acctRows());
  R.h('6. Money flow ledger'); R.table(['Flow', 'From layer', 'From a/c', 'To', 'Date/Time', 'Traced', 'Txn amt', 'UTR', 'After receipt', 'Match', 'Why matched', 'Source'], d.flows.slice().sort((a, b) => a.layerFrom - b.layerFrom || a.ts - b.ts).map(flowRow), { styles: { fontSize: 6.5, cellPadding: 2 } });
  const common = Array.from(d.acctRes.entries()).filter(([, r]) => r.origins.length > 1);
  R.h('7. Accounts receiving from multiple disputed transactions'); R.table(['Account', 'Layer', 'Disputed txns', 'Sending accounts', 'Traced in'], common.map(([id, r]) => [(IX.acctById.get(id) || {}).acctNo, layerName(r.layer), r.origins.length, r.fromAccts.length, inrP(r.tin)]));
  const ipx = IPX();
  R.h('8. Login IP correlation'); R.table(['Txn', 'Account', 'Txn time', 'Login time', 'IP:port', 'Type', 'How matched', 'IPDR subscriber'], Array.from(ipx.txLogin.entries()).filter(([id]) => c.work.disputed.includes(id) || d.flows.some(f => f.debit === id)).map(([id, lg]) => { const tx = IX.txById.get(id); return [id, (IX.acctById.get(tx.acctId) || {}).acctNo, fmtDT(tx.ts, tx.hasTime), fmtDT(lg.log.ts), lg.ip + (lg.port ? ':' + lg.port : ''), lg.cls.label, lg.how, lg.ipdr ? lg.ipdr.nums.join(', ') : 'pending']; }));
  R.table(['Shared IP', 'Type', 'Accounts', 'Closest logins apart'], ipx.sharedIp.map(s => [s.ip, s.cls.label, s.accts.map(a => (IX.acctById.get(a) || {}).acctNo).join(', '), s.close === Infinity ? '' : durTxt(s.close)]));
  if (c.telecom.cdr.length) { const tel = T(); R.h('9. Telecom correlation (CDR)');
    R.table(['Number A', 'Number B', 'Events', 'SMS', 'Minutes', 'First', 'Last', 'Complainant'], tel.direct.slice(0, 200).map(x => [numLabel(x.a), numLabel(x.b), x.n, x.sms, Math.round(x.dur / 60), fmtDT(x.first), fmtDT(x.last), x.complainant ? 'YES' : '']));
    R.table(['Common contact', 'Seen in target CDRs', 'Events'], tel.common.filter(x => x.targets.length >= 2).slice(0, 100).map(x => [numLabel(x.num), x.targets.join(', '), x.n]));
    R.table(['IMEI', 'Numbers'], tel.sharedImei.map(x => [x.imei, x.nums.map(numLabel).join(', ')])); }
  R.h('10. Transaction correlation matrix'); const w = c.work.settings.cdrWindowMin;
  R.table(['Txn', 'When', 'Amount', 'Account', 'Own calls', 'Complainant calls', 'SMS/OTP', 'Login IP', 'IPDR no.', 'Cells', 'Strength'], uniq(d.seeds.map(s => s.id).concat(d.flows.map(f => f.debit))).map(id => IX.txById.get(id)).filter(Boolean).slice(0, 600).map(tx => { const k = txCorrelation(tx, w); return [tx.id, fmtDT(tx.ts, tx.hasTime), inrP(tx.dr || tx.cr), (IX.acctById.get(tx.acctId) || {}).acctNo, k.ownCalls.length, k.compCalls.length, k.sms.length + (k.sms.some(s => s.otp) ? ' (OTP)' : ''), k.login ? k.login.ip : '', k.login && k.login.ipdr ? k.login.ipdr.nums.join(',') : '', k.cells.join(','), k.strength]; }));
  R.h('11. Investigation leads'); R.table(['Lead', 'Priority', 'Status', 'Observation', 'Supporting data'], buildLeads().slice(0, 300).map(l => [l.id.split('-').slice(0, 2).join('-'), l.sev.toUpperCase(), l.state.status, l.title, l.detail]));
  const rq = requisitions(); R.h('12. Pending requisitions');
  R.table(['Account/UPI', 'Bank', 'IFSC', 'Layer', 'Traced amount', 'Reason'], rq.stmt.map(x => [x.acctNo || x.upi, x.bank, x.ifsc, layerName(x.layer), inrP(x.amount), x.reason]));
  R.table(['Number (CDR pending)', 'Linked to'], rq.cdr.map(x => [x.num, x.links])); R.table(['IP (IPDR pending)', 'Port', 'IST', 'UTC'], rq.ipdr.map(x => [x.ip, x.port || 'n/a', fmtDT(x.ts), fmtDT(x.ts - 330 * 60000)]));
  R.h('13. Source documents'); R.table(['Import', 'File', 'Kind', 'Imported', 'By', 'Rows added', 'Unparsed', 'SHA-256'], c.work.imports.map(i => [i.id, i.file, i.kind, i.at, i.by, i.added, i.rejectCount, i.hash]), { styles: { fontSize: 6.5 } });
  R.save('Complete_Investigation_Report');
}
function reportAccount(id) {
  const a = IX.acctById.get(id); const d = D(); const r = d.acctRes.get(id) || {}; const s = a.stmt; const R = pdfDoc('Account Profile Report — ' + a.acctNo);
  R.h('Account'); R.kv([['Account number', a.acctNo], ['Holder', a.holder], ['Bank / IFSC / Branch', `${a.bank} / ${a.ifsc} / ${a.branch}`], ['Role / Layer', `${a.role || '—'} / ${layerName(acctLayer(id))}`], ['Registered mobile', a.mobiles.join(', ')], ['Alternate numbers', a.altMobiles.join(', ')], ['E-mail / PAN', a.emails.join(', ') + ' / ' + a.pan], ['UPI IDs', (a.kyc.upi || []).join(', ')], ['Address', a.address]]);
  if (s) { R.h('Statement period analysis'); R.kv([['Period', fmtDate(s.from) + ' to ' + fmtDate(s.to)], ['Opening / closing balance', inrP(s.opening) + ' / ' + inrP(s.closing)], ['Transactions', `${s.n} (${s.nCr} credits, ${s.nDr} debits)`], ['Total credit / debit', inrP(s.totCr) + ' / ' + inrP(s.totDr)], ['Largest credit / debit', inrP(s.maxCr) + ' / ' + inrP(s.maxDr)], ['Average credit / debit', inrP(s.avgCr) + ' / ' + inrP(s.avgDr)], ['Channels', Object.entries(s.channels).map(([k, v]) => k + ' ' + v).join(', ')]]); }
  R.h('Traced funds'); R.kv([['Traced in', inrP(r.tin || 0)], ['Traced onward', inrP(r.tout || 0)], ['Cash / ATM', inrP(r.cash || 0)], ['Possibly available', inrP(r.retained || 0)]]);
  R.table(['From', 'Date/Time', 'Amount', 'Match', 'Why'], d.flows.filter(f => f.toAcct === id).map(f => [(IX.acctById.get(f.fromAcct) || {}).acctNo, fmtDT(f.ts, f.hasTime), inrP(f.amt), f.strength, (f.reasons || []).join('; ')]));
  R.table(['To', 'Date/Time', 'Amount', 'After receipt', 'Match'], d.flows.filter(f => f.fromAcct === id).map(f => [f.toAcct ? (IX.acctById.get(f.toAcct) || {}).acctNo : f.toExt.label, fmtDT(f.ts, f.hasTime), inrP(f.amt), f.gap != null ? durTxt(f.gap) : '', f.strength]));
  const logs = IPX().byAcct.get(id) || []; R.h('Login IPs'); R.table(['Time', 'IP', 'Port', 'Type', 'Channel', 'Device'], logs.slice(-200).map(l => [fmtDT(l.ts), l.ip, l.port || '', ipClass(l.ip).label, l.channel, l.device]));
  R.h('Leads involving this account'); R.table(['Priority', 'Observation', 'Supporting data'], buildLeads().filter(l => l.ents.includes(id)).map(l => [l.sev, l.title, l.detail]));
  R.h('Transactions'); R.table(['Txn', 'Date', 'Time', 'Debit', 'Credit', 'Balance', 'Channel', 'UTR', 'Narration', 'Source row'], (IX.txByAcct.get(id) || []).slice(0, 3000).map(t => [t.id, fmtDate(t.ts), t.hasTime ? fmtTime(t.ts) : 'n/a', t.dr ? inrP(t.dr) : '', t.cr ? inrP(t.cr) : '', t.bal == null ? '' : inrP(t.bal), t.channel, t.utr, t.narr.slice(0, 60), (t.src.page ? 'p' + t.src.page + ' ' : '') + 'r' + t.src.row]), { styles: { fontSize: 6.5, cellPadding: 1.8 } });
  R.save('Account_' + a.acctNo);
}
function reportTransaction(id) {
  const t = IX.txById.get(id); const a = IX.acctById.get(t.acctId); const d = D(); const k = txCorrelation(t); const R = pdfDoc('Transaction Report — ' + id, false);
  R.h('Transaction'); R.kv([['Transaction ID', id], ['Account', a.acctNo + ' ' + a.holder + ' (' + a.bank + ')'], ['Date / time', fmtDate(t.ts) + ' ' + (t.hasTime ? fmtTime(t.ts) : '(transaction time unavailable in source statement)')], ['Amount', (t.dr ? 'Debit ' : 'Credit ') + inrP(t.dr || t.cr)], ['Channel / UTR / Ref', `${t.channel} / ${t.utr} / ${t.ref}`], ['Narration', t.narr], ['Disputed', S.cur.work.disputed.includes(id) ? 'Yes' : 'No'], ['Source', `${t.src.file} ${t.src.sheet || ''} ${t.src.page ? 'page ' + t.src.page : ''} row ${t.src.row}`], ['Original text', t.raw]]);
  R.h('Backward trace'); R.table(['Debit a/c', 'Debit', 'Credit a/c', 'Credit', 'Match'], traceBackward(id).map(b => [(IX.acctById.get(b.debit.acctId) || {}).acctNo, inrP(b.debit.dr) + ' ' + fmtDT(b.debit.ts, b.debit.hasTime), (IX.acctById.get(b.credit.acctId) || {}).acctNo, inrP(b.credit.cr), b.m ? b.m.strength + ' — ' + b.m.reasons.join('; ') : '']));
  R.h('Forward trace'); R.table(['Depth', 'From', 'To', 'Traced amount', 'When', 'Match'], traceForward(id, 8).map(f => [f.depth, (IX.acctById.get(f.fromAcct) || {}).acctNo, f.toAcct ? (IX.acctById.get(f.toAcct) || {}).acctNo : f.toExt.label, inrP(f.amt), fmtDT(f.ts, f.hasTime), f.strength]));
  R.h(`Time correlation (±${S.cur.work.settings.cdrWindowMin} min)`); R.table(['Time', 'Type', 'Detail'], k.calls.map(r => [fmtDT(r.ts), r.kind + ' ' + r.dir, `${r.target} ${r.dir === 'IN' ? '<-' : '->'} ${r.other} ${r.dur}s cell ${r.cell} IMEI ${r.imei}`]).concat(k.sms.map(s => [fmtDT(s.ts), 'SMS' + (s.otp ? '/OTP' : ''), s.msisdn + ' <- ' + s.sender + ': ' + s.msg.slice(0, 80)])).sort((x, y) => x[0].localeCompare(y[0])));
  if (k.login) { R.h('Login / IP'); R.kv([['Login time', fmtDT(k.login.log.ts)], ['IP / port', k.login.ip + (k.login.port ? ':' + k.login.port : '')], ['Type', k.login.cls.label + ' — ' + (k.login.cls.note || '')], ['How matched', k.login.how], ['IPDR result', k.login.ipdr ? k.login.ipdr.nums.join(', ') + ' (' + k.login.ipdr.note + ')' : 'Pending']]); }
  R.h('Limitations'); R.p(METHOD[3]); R.save('Transaction_' + id);
}
function reportTelecom() {
  const tel = T(); const R = pdfDoc('CDR / Suspected Number Correlation Report');
  R.h('Target CDRs'); R.table(['Target', 'Linked to', 'Events', 'In/Out', 'Contacts', 'IMEIs', 'First', 'Last'], tel.targets.map(x => [x.num, x.info ? x.info.links.map(l => l.kind + ' ' + l.label).join('; ') : 'not linked', x.n, x.inc + '/' + x.out, x.contacts, x.imeis.join(', '), fmtDT(x.first), fmtDT(x.last)]));
  R.h('Investigation numbers'); R.table(['Number', 'Role', 'Source', 'Person', 'Remarks', 'CDR events', 'Seen in other CDRs'], S.cur.work.numbers.map(n => [n.num, n.role, n.source, n.person, n.remarks, (tel.byTarget.get(n.num) || []).length, S.cur.telecom.cdr.filter(r => r.other === n.num).length]));
  R.h('Direct contact between known numbers'); R.table(['A', 'B', 'Events', 'Minutes', 'First', 'Last', 'Complainant'], tel.direct.map(x => [numLabel(x.a), numLabel(x.b), x.n, Math.round(x.dur / 60), fmtDT(x.first), fmtDT(x.last), x.complainant ? 'YES' : '']));
  R.h('Common contacts'); R.table(['Number', 'Targets', 'Events'], tel.common.slice(0, 300).map(x => [numLabel(x.num), x.targets.join(', '), x.n]));
  R.h('Shared handsets'); R.table(['IMEI', 'Numbers'], tel.sharedImei.map(x => [x.imei, x.nums.join(', ')]));
  R.h('Cell-site co-location (not exact location)'); R.table(['A', 'B', 'Cell', 'Address', 'Times'], tel.colocPairs.slice(0, 300).map(x => [x.a, x.b, x.cell, x.addr, x.n]));
  R.save('CDR_Correlation');
}
function reportPatterns() {
  const r = patternQuery({ from: PAT.from ? Date.parse(PAT.from + 'T00:00:00Z') : null, to: PAT.to ? Date.parse(PAT.to + 'T00:00:00Z') : null, days: PAT.days, amount: +PAT.amount || 0, tol: +PAT.tol || 0, dir: PAT.dir, accts: PAT.acct ? new Set([PAT.acct]) : null });
  const R = pdfDoc('NDPS / Financial Pattern Report');
  R.h('Selection'); R.kv([['Period', (PAT.from || 'start') + ' to ' + (PAT.to || 'end')], ['Days', PAT.days.size ? Array.from(PAT.days).map(i => DOW[i]).join(', ') : 'All'], ['Amount', PAT.amount ? inrP(+PAT.amount) + ' ± ' + (PAT.tol || 0) : 'Any'], ['Transactions', r.rows.length]]);
  R.p('Patterns are observations for verification. Repeated amounts or weekend activity do not by themselves indicate criminal purpose.');
  R.h('Repeated amounts'); R.table(['Amount', 'Count', 'Dates', 'Weekend', 'Accounts', 'Counterparties', 'UPI', 'Mobiles', 'CDR near'], r.groups.filter(g => g.n >= 2).slice(0, 200).map(g => [inrP(g.amt, 0), g.n, g.dates, g.weekend, g.accts, g.cps, g.upis, g.mobiles, g.cdrHits]));
  R.h('Transactions'); R.table(['Date', 'Day', 'Time', 'Account', 'Dr/Cr', 'Amount', 'Counterparty', 'UTR', 'Narration'], r.rows.slice(0, 3000).sort((a, b) => a.ts - b.ts).map(t => [fmtDate(t.ts), DOW[dow(t.ts)], t.hasTime ? fmtTime(t.ts) : 'n/a', (IX.acctById.get(t.acctId) || {}).acctNo, t.dr ? 'Dr' : 'Cr', inrP(t.dr || t.cr), t.cpAcct[0] || t.upi || '', t.utr, t.narr.slice(0, 60)]), { styles: { fontSize: 6.5 } });
  R.save('Pattern_Report');
}
function exportWorkbook(only) {
  const c = S.cur; const d = D(); const wb = XLSX.utils.book_new(); const add = (n, rows) => { if (only && !only.includes(n)) return; XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(rows.map(r => r.map(v => safeCell(v == null ? '' : v)))), n); };
  add('Case', [['Field', 'Value']].concat(caseKv()).concat([['Generated', nowStamp()], ['By', S.user.email]]));
  add('Layers', [['Layer', 'Accounts', 'Traced in', 'Cash out', 'Possibly available']].concat(Array.from(d.byLayer.entries()).sort((a, b) => a[0] - b[0]).map(([l, b]) => [layerName(l), b.accts, round2(b.tin), round2(b.cash), round2(b.retained)])));
  add('Accounts', [['Layer', 'Role', 'Account', 'Holder', 'Bank', 'IFSC', 'Registered mobile', 'Alternate', 'Email', 'PAN', 'Traced in', 'Onward', 'Cash', 'Possibly available', 'Statement']].concat(c.accts.map(a => { const r = d.acctRes.get(a.id) || {}; return [layerName(acctLayer(a.id)), a.role, a.acctNo, a.holder, a.bank, a.ifsc, a.mobiles.join(', '), a.altMobiles.join(', '), a.emails.join(', '), a.pan, r.tin || 0, r.tout || 0, r.cash || 0, r.retained || 0, IX.txByAcct.has(a.id) ? 'Yes' : 'Pending']; })));
  add('Trail', [['Flow', 'From layer', 'From account', 'To', 'Date/Time', 'Traced amount', 'Txn amount', 'UTR', 'After receipt', 'Match', 'Why', 'Source']].concat(d.flows.map(f => { const r = flowRow(f); r[5] = f.amt; r[6] = f.full; return r; })));
  add('Transactions', [['ID', 'Account', 'Date', 'Time', 'Debit', 'Credit', 'Balance', 'Channel', 'UTR', 'Ref', 'Counterparty', 'UPI', 'Disputed', 'Flags', 'Narration', 'Source file', 'Sheet/Page', 'Row']].concat(c.txns.map(t => [t.id, (IX.acctById.get(t.acctId) || {}).acctNo, fmtDate(t.ts), t.hasTime ? fmtTime(t.ts) : '', t.dr || '', t.cr || '', t.bal, t.channel, t.utr, t.ref, t.cpAcct.join(' '), t.upi, c.work.disputed.includes(t.id) ? 'YES' : '', t.flags.join(' '), t.narr, t.src.file, t.src.page || t.src.sheet, t.src.row])));
  add('Login IP chain', [['Txn', 'Account', 'Txn time', 'Login time', 'IP', 'Port', 'Type', 'How', 'IPDR numbers']].concat(Array.from(IPX().txLogin.entries()).map(([id, lg]) => { const t = IX.txById.get(id); return [id, (IX.acctById.get(t.acctId) || {}).acctNo, fmtDT(t.ts, t.hasTime), fmtDT(lg.log.ts), lg.ip, lg.port || '', lg.cls.label, lg.how, lg.ipdr ? lg.ipdr.nums.join(', ') : '']; })));
  if (c.telecom.cdr.length) { const tel = T(); add('CDR hits', [['Type', 'A', 'B / targets', 'Events', 'Detail']].concat(tel.direct.map(x => ['Direct', x.a, x.b, x.n, x.complainant ? 'Complainant' : '']), tel.common.slice(0, 2000).map(x => ['Common contact', x.num, x.targets.join(', '), x.n, '']), tel.sharedImei.map(x => ['Shared IMEI', x.imei, x.nums.join(', '), '', '']))); }
  add('Leads', [['Lead', 'Priority', 'Status', 'Observation', 'Supporting data', 'Note']].concat(buildLeads().map(l => [l.id, l.sev, l.state.status, l.title, l.detail, l.state.note || ''])));
  add('Source documents', [['Import', 'File', 'Kind', 'Format', 'Imported', 'By', 'Added', 'Duplicates', 'Unparsed', 'SHA-256']].concat(c.work.imports.map(i => [i.id, i.file, i.kind, i.type, i.at, i.by, i.added, i.dups, i.rejectCount, i.hash])));
  add('Audit', [['Time', 'User', 'Action', 'Detail', 'Hash']].concat(c.audit.map(a => [a.ts, a.user, a.action, a.detail, a.h])));
  XLSX.writeFile(wb, `CFITS_${fileSafe(c.meta.id)}_${only ? only.join('_') : 'Workbook'}_${isoDate(nowWall())}.xlsx`); audit('Exported Excel workbook', only ? only.join(',') : 'full');
}
VIEWS.reports = el => {
  const c = S.cur;
  const items = [['Complete Investigation Report', 'Case details, methodology, seeds, trail accounts, flow ledger, IP & CDR correlation, leads, requisitions and source documents (PDF).', () => reportComplete()], ['Case Summary', 'Two-page summary with layer totals and high-priority leads (PDF).', () => reportComplete('summary')],
    ['Money Flow / Trail workbook', 'Layers, accounts and flow ledger (Excel).', () => exportWorkbook(['Case', 'Layers', 'Accounts', 'Trail'])], ['Full analysis workbook', 'All sheets including every transaction, IP chain, CDR hits, leads, source hashes and audit log (Excel).', () => exportWorkbook()],
    ['CDR / Suspected Number Report', 'Targets, investigation numbers, direct hits, common contacts, shared IMEI, co-location (PDF).', () => reportTelecom()], ['NDPS / Pattern Report', 'Uses the current selection on the Patterns page (PDF).', () => reportPatterns()],
    ['Individual Account Report', 'Pick an account (PDF).', async () => { const v = await promptBox('Account report', [{ label: 'Account', type: 'select', options: c.accts.map(a => a.acctNo + ' — ' + (a.holder || '')) }]); if (v) reportAccount(c.accts.find(a => v[0].startsWith(a.acctNo + ' ')).id); }],
    ['Transaction Report', 'Enter a transaction ID (PDF). Also available from any transaction.', async () => { const v = await promptBox('Transaction report', [{ label: 'Transaction ID', value: c.work.disputed[0] || '' }]); if (v && IX.txById.get(v[0].trim())) reportTransaction(v[0].trim()); else if (v) toast('Unknown transaction ID', 'warn'); }],
    ['Encrypted case package (.enc)', 'Portable AES-256-GCM package for transfer/archive. Needs the vault passphrase to open.', async () => { const b = await Vault.pack(casePackage(c)); downloadBlob(new Blob([b]), `CFITS_CASE_${fileSafe(c.meta.id)}_${isoDate(nowWall())}.enc`); audit('Exported encrypted package'); }],
    ['Plain JSON export', 'Unencrypted — only for transfer to another analysis system under your control.', async () => { if (await confirmBox('Unencrypted export', 'This file will contain all case data <b>without encryption</b>. Continue?', 'Export', true)) { downloadBlob(new Blob([JSON.stringify(casePackage(c), null, 1)], { type: 'application/json' }), `CFITS_CASE_${fileSafe(c.meta.id)}.json`); audit('Exported UNENCRYPTED JSON'); } }]];
  el.innerHTML = pageHead('Reports & Export', 'Professional reports with case number, confidentiality marking, officer, generation time, page numbers and source references. Every export is recorded in the audit log.') +
    `<div class="grid g3">${items.map((x, i) => `<div class="card"><h3>${esc(x[0])}</h3><p class="small muted">${esc(x[1])}</p><button class="btn-p" data-r="${i}">Generate</button></div>`).join('')}</div>`;
  $$('[data-r]', el).forEach(b => b.onclick = async () => { b.disabled = true; try { await items[+b.dataset.r][2](); } catch (e) { console.error(e); toast('Report failed: ' + e.message, 'err'); } b.disabled = false; });
};
