/* ============================ LEADS (professional board) ============================
   Every lead: category, priority score, the evidence behind it, and the next action.
   Location-wise tracing groups the strongest location leads with the nearest police station. */
const LEAD_CAT = { R01: 'Money trail', R02: 'Money trail', R03: 'Recovery', R04: 'Cash-out', R05: 'Pending data', R05B: 'Pending data', R06: 'Digital / IP', R06B: 'Digital / IP', R07: 'Digital / IP', R08: 'Digital / IP', R09: 'Telecom', R09B: 'Telecom', R10: 'Telecom', R11: 'Handset', R12: 'Location', R13: 'Identity', R15: 'Behaviour', R16: 'Behaviour', R17: 'Behaviour', R18: 'Cash-out', R19: 'Money trail', R20: 'Pending data' };
const LEAD_ACT = { R01: 'Treat as primary mule — request KYC, full statement, login IPs; examine account holder.', R02: 'Rapid pass-through account — request KYC and login IP logs; check linked accounts.', R03: 'Send debit-freeze / hold notice (Sec. 106 BNSS) to the bank today.', R04: 'Request ATM / branch CCTV and EJ log (ATM footage letter).', R05: 'Send Sec. 94 BNSS notice for the statement to continue the trail.', R05B: 'Identify the beneficiary accounts (notice to the remitting bank).', R06: 'Request IPDR for this IP with exact time and port.', R06B: 'Request device details from the banks; same device operates several accounts.', R07: 'Request IPDR for the session IP; compare with complainant’s usual IPs.', R08: 'Resolved subscriber — verify and examine.', R09: 'Obtain CAF / KYC of the number; examine the complainant on the calls.', R09B: 'Obtain CAF of both numbers; check relationship.', R10: 'Common contact — obtain CAF and CDR.', R11: 'Request IMEI-trace CDR from all operators.', R12: 'Cell-site overlap — verify location with tower dump if needed.', R13: 'Same identifier across accounts — confirm with KYC.', R15: 'Check who sent the validation credits.', R16: 'Check counterparties of the repeated amounts.', R17: 'Weekend pattern — compare with CDR location.', R18: 'Request ATM / branch CCTV for the cash withdrawal.', R19: 'Resolve ambiguous links in Money Trail.', R20: 'Review the file in Data Quality.' };
function buildLeads2() {
  return intelCache('leads2', () => {
    const c = S.cur; const out = buildLeads().map(l => Object.assign(l, { cat: LEAD_CAT[l.rule] || 'Other', action: LEAD_ACT[l.rule] || '', loc: null }));
    const st = id => c.work.leadState[id] || { status: 'New' };
    const L = (rule, sev, key, cat, title, detail, action, ents, loc) => { const id = 'LD-' + rule + '-' + String(key).slice(0, 60); out.push({ id, rule, sev, cat, title, detail, action, ents: ents || [], loc: loc || null, state: st(id) }); };
    try {
      const F = anFusion();
      for (const x of F.commonCells.slice(0, 30)) L('L01', 'high', x.cell || x.addr, 'Location', `Different accounts operated from the same place: ${x.addr || 'cell ' + x.cell}`, `${x.accts.length} accounts (${x.accts.join(', ')}) · numbers ${x.nums.join(', ')} · ${x.n} money events · ${inr(x.amt)}`, 'Probable operating base — request tower dump / field verification; coordinate with the local police station.', x.accts, { addr: x.addr, cell: x.cell, lat: x.lat, lon: x.lon, num: x.nums[0] });
      for (const x of F.commonImei.slice(0, 30)) L('L02', 'high', x.imei, 'Handset', `One handset (IMEI ${x.imei}) used with ${x.nums.length} numbers`, x.nums.map((n, i) => n + (x.names[i] ? ' (' + x.names[i] + ')' : '')).join(', ') + (x.accts.length ? ' · accounts ' + x.accts.join(', ') : ''), 'Request IMEI-trace CDR from all operators; the same person / gang operates these numbers.', x.accts);
      for (const p of numberProfile().filter(p => p.night[0] && p.night[0].pct >= 40 && /accused|suspect|layer/i.test(p.role + ' ' + (p.acct ? acctType(p.acct) : ''))).slice(0, 40)) L('L03', 'med', p.num, 'Location', `Probable residence of ${p.num}${p.name ? ' (' + p.name + ')' : ''}: ${p.night[0].addr || 'cell ' + p.night[0].cell}`, `${p.night[0].pct}% of night-time records (10 pm – 6 am) on this cell.`, 'Verify the address through the local police station / field enquiry.', p.acct ? [p.acct.id] : [], Object.assign({ num: p.num }, p.night[0]));
    } catch (e) { console.warn(e); }
    try { const V = verifyRows(); const bad = V.l1.filter(r => /NOT VERIFIED/.test(r.status)); if (bad.length) L('L04', 'med', 'verif', 'Money trail', `${bad.length} reported transaction(s) do not match the bank statements`, bad.slice(0, 6).map(r => (r.utr || '') + ' ' + inr(r.amt)).join(' · '), 'Open Money Trail Verification and review each one; ask the bank to confirm.', []); } catch {}
    const holds = c.work.ncrp.filter(r => r.hold > 0 || r.action === 'HOLD'); if (holds.length) L('L05', 'high', 'hold', 'Recovery', `${inr(sum(holds, r => r.hold || r.amount))} is on hold in ${uniq(holds.map(r => r.acctNo)).length} account(s)`, holds.slice(0, 6).map(r => r.acctNo + ' ' + inr(r.hold || r.amount)).join(' · '), 'Keep the hold alive and start the process to return the amount to the victim as per law.', []);
    try { for (const a of caseAtmRows().filter(a => a.info || a.place).slice(0, 30)) L('L06', 'high', a.atmId || a.place, 'Cash-out', `Cash withdrawn at ATM ${a.atmId || ''} ${a.info ? '— ' + [a.info.address, a.info.city, a.info.state].filter(Boolean).join(', ') : a.place}`, `${a.n} withdrawal(s) · ${inr(a.amount)} · ${a.first ? fmtDT(a.first) : ''} · from ${a.accts.join(', ')}`, 'Send the ATM footage letter for these dates and times; ask the local police station to identify the person on CCTV.', [], a.info ? { addr: [a.info.address, a.info.city].filter(Boolean).join(', '), lat: a.info.lat, lon: a.info.lon } : { addr: a.place }); } catch {}
    for (const r of c.work.ncrp.filter(r => r.action === 'CHEQUE').slice(0, 30)) L('L09', 'high', r.id, 'Cash-out', `Cheque withdrawal ${inr(r.amount)} from ${r.acctNo} (${r.bank})`, `${r.ts ? fmtDT(r.ts, r.hasTime) : ''} · cheque ${r.chequeNo || 'no. not given'} · ${r.remarks || ''}`, 'Send the cheque-withdrawal letter: cheque copy, encashing person’s ID, branch CCTV.', []);
    for (const x of anDormant().filter(x => x.verdict.startsWith('Dormant')).slice(0, 30)) L('L07', 'med', x.a.id, 'Behaviour', `Dormant account ${acctName(x.a)} became active just before / during the fraud`, `Silent ${x.gap} days, then ${x.postN} transactions (${inr(x.postAmt)}) in 30 days.`, 'Likely a rented / sold mule account — examine the account holder and who controls the credentials.', [x.a.id]);
    const TT = anTest(); for (const x of TT.cpLinks.slice(0, 20)) L('L08', 'med', x.cp, 'Behaviour', `Same sender tested ${x.accts.length} accounts with small amounts`, `${x.cp} → ${x.accts.join(', ')}`, 'The sender checked the mule accounts — identify the sender account / UPI.', []);
    const sevO = { high: 0, med: 1, low: 2 }; const catO = ['Location', 'Handset', 'Recovery', 'Cash-out', 'Money trail', 'Digital / IP', 'Telecom', 'Identity', 'Pending data', 'Behaviour', 'Other'];
    return out.map(l => Object.assign(l, { score: (l.sev === 'high' ? 70 : l.sev === 'med' ? 45 : 20) + (['Location', 'Handset', 'Recovery'].includes(l.cat) ? 20 : ['Cash-out', 'Digital / IP'].includes(l.cat) ? 10 : 0) + Math.min(10, (l.ents || []).length * 2) }))
      .sort((a, b) => sevO[a.sev] - sevO[b.sev] || b.score - a.score || catO.indexOf(a.cat) - catO.indexOf(b.cat));
  });
}
const LD = { cat: '', sev: '', st: '' };
const CAT_ICON = { 'Location': 'pin', 'Handset': 'phone', 'Recovery': 'shield', 'Cash-out': 'bank', 'Money trail': 'flow', 'Digital / IP': 'globe', 'Telecom': 'phone', 'Identity': 'users', 'Pending data': 'mail', 'Behaviour': 'chart', 'Other': 'flag' };
VIEWS.leads = async el => {
  await GEO.ready(); const leads = buildLeads2(); const cats = uniq(leads.map(l => l.cat));
  const f = leads.filter(l => (!LD.cat || l.cat === LD.cat) && (!LD.sev || l.sev === LD.sev) && (!LD.st || l.state.status === LD.st));
  const locs = leads.filter(l => l.loc && (l.loc.addr || l.loc.cell)).slice(0, 12);
  el.innerHTML = pageHead('Leads', 'What to do next, ranked. Each lead shows the evidence behind it and the recommended action. A lead is an observation to verify — never proof of guilt.', `<button id="lX">⇩ Excel</button><button id="lP" class="btn-p">⎙ Leads report (PDF)</button>`) +
    `<div class="grid g4" style="margin-bottom:14px">${kpi('High priority', nfmt(leads.filter(l => l.sev === 'high').length), 'act today', 'rgba(255,77,94,.35)')}${kpi('Location leads', nfmt(leads.filter(l => l.cat === 'Location' || l.cat === 'Handset').length), 'where the accused operate', 'rgba(255,46,136,.35)')}${kpi('Recovery / cash-out', nfmt(leads.filter(l => l.cat === 'Recovery' || l.cat === 'Cash-out').length), 'hold · ATM · cheque', 'rgba(0,255,157,.3)')}${kpi('Verified / closed', nfmt(leads.filter(l => ['Verified', 'Closed', 'Not Relevant'].includes(l.state.status)).length), `of ${leads.length} leads`, 'rgba(0,229,255,.3)')}</div>
    ${locs.length ? `<div class="card" style="margin-bottom:14px"><h3>📍 Location-wise tracing</h3><div class="loc-board">${locs.map(l => `<div class="loc-card s-${l.sev}"><div class="small dim">${esc(l.cat)} · ${esc(l.rule)}</div><b>${esc(l.loc.addr || 'Cell ' + l.loc.cell)}</b><div class="small muted">${esc(l.title.replace(/:.*$/, ''))}</div><div class="small" style="margin-top:6px">🚓 ${psHtml(l.loc)}</div><div class="row" style="margin-top:6px">${l.loc.lat != null || l.loc.addr ? `<a class="btn-sm" target="_blank" rel="noopener noreferrer" href="${gmapsUrl(l.loc.addr || '', l.loc.lat, l.loc.lon)}">⌖ Map</a>` : ''}<button class="btn-sm" data-lt="${esc(l.id)}">＋ Task</button></div></div>`).join('')}</div></div>` : ''}
    <div class="card" style="margin-bottom:10px"><div class="row" style="flex-wrap:wrap;gap:6px"><span class="chip ${!LD.cat ? 'on' : ''}" data-lc="">All (${leads.length})</span>${cats.map(k => `<span class="chip ${LD.cat === k ? 'on' : ''}" data-lc="${esc(k)}">${esc(k)} (${leads.filter(l => l.cat === k).length})</span>`).join('')}<span class="grow"></span>
      <select id="lSev" style="width:auto"><option value="">All priorities</option><option value="high" ${LD.sev === 'high' ? 'selected' : ''}>High</option><option value="med" ${LD.sev === 'med' ? 'selected' : ''}>Medium</option><option value="low" ${LD.sev === 'low' ? 'selected' : ''}>Low</option></select>
      <select id="lSt" style="width:auto"><option value="">All statuses</option>${LEAD_STATUS.map(s => `<option ${LD.st === s ? 'selected' : ''}>${s}</option>`).join('')}</select></div></div>
    <div id="lL">${f.slice(0, 300).map(l => `<div class="lead2 s-${l.sev}"><div class="l2-ic" style="--pc:${l.sev === 'high' ? '#ff4d5e' : l.sev === 'med' ? '#ffb300' : '#2f9bff'}">${icon(CAT_ICON[l.cat] || 'flag')}</div>
      <div class="l2-b"><div class="row sb" style="flex-wrap:wrap"><div>${badge(l.sev === 'high' ? 'HIGH' : l.sev === 'med' ? 'MEDIUM' : 'LOW', l.sev === 'high' ? 'red' : l.sev === 'med' ? 'amber' : 'blue')} ${badge(l.cat, 'cyan')} <span class="small dim mono">${esc(l.rule)} · score ${l.score}</span></div>
        <div class="row no-print"><select class="btn-sm" data-ls="${esc(l.id)}">${LEAD_STATUS.map(s => `<option ${s === l.state.status ? 'selected' : ''}>${s}</option>`).join('')}</select><button class="btn-sm" data-lt="${esc(l.id)}">＋ Task</button></div></div>
        <div class="l2-t">${esc(l.title)}</div><div class="small muted">${esc(l.detail)}</div>${l.action ? `<div class="l2-a">➜ ${esc(l.action)}</div>` : ''}${l.state.note ? `<div class="small" style="margin-top:3px">📝 ${esc(l.state.note)}</div>` : ''}</div></div>`).join('') || emptyState('No leads for this filter.')}</div>`;
  $$('[data-lc]', el).forEach(b => b.onclick = () => { LD.cat = b.dataset.lc; go('leads'); });
  $('#lSev', el).onchange = e => { LD.sev = e.target.value; go('leads'); }; $('#lSt', el).onchange = e => { LD.st = e.target.value; go('leads'); };
  const by = new Map(leads.map(l => [l.id, l]));
  $$('[data-ls]', el).forEach(s => s.onchange = async () => { const id = s.dataset.ls; const note = ['Not Relevant', 'Verified', 'Closed'].includes(s.value) ? ((await promptBox('Lead ' + s.value, [{ label: 'Reason / note (recorded in audit log)', type: 'textarea' }])) || [''])[0] : ''; S.cur.work.leadState[id] = { status: s.value, note, by: S.user.email, at: nowStamp() }; markDirty('work'); await audit('Lead ' + s.value, id + ' ' + note); S.derived && (S.derived.intel = null); go('leads'); });
  $$('[data-lt]', el).forEach(b => b.onclick = () => { const l = by.get(b.dataset.lt); taskDialog({ task: (l ? l.title + ' — ' + (l.action || '') : b.dataset.lt).slice(0, 300), lead: b.dataset.lt }); });
  const cols = [{ label: 'Priority', k: 'sev' }, { label: 'Score', k: 'score' }, { label: 'Category', k: 'cat' }, { label: 'Lead', k: 'title' }, { label: 'Evidence', k: 'detail' }, { label: 'Next action', k: 'action' }, { label: 'Location', get: l => l.loc ? (l.loc.addr || l.loc.cell || '') : '' }, { label: 'Nearest PS', get: l => l.loc ? psHtml(l.loc, true) : '' }, { label: 'Status', get: l => l.state.status }, { label: 'Note', get: l => l.state.note || '' }, { label: 'ID', k: 'id' }];
  $('#lX', el).onclick = () => xlsxBook('Leads', [{ name: 'Leads', cols, rows: leads }]);
  $('#lP', el).onclick = () => { const R = pdfDoc('Investigation Leads'); R.h('Case details'); R.kv(caseKv()); for (const cat of cats) { R.h(cat); R.table(['Priority', 'Lead', 'Evidence', 'Next action', 'Status'], leads.filter(l => l.cat === cat).slice(0, 80).map(l => [l.sev.toUpperCase(), l.title, l.detail.slice(0, 220), l.action, l.state.status])); } R.p('Leads are observations derived from the uploaded records and must be verified before any action against a person.'); R.save('Leads'); };
};
